### ISSUE TITLE
Zim building fails when there are spaces in the Title field

### ISSUE THREAD

**Issue by sodabottle** [tecoholic/zimbalaka#8]
When i test for more files (tested for 101 and 25) zim wasnt generated even after three hours.

**Comment by tecoholic** [comment]
Going over the log:

```
[2015-05-09 07:30:41,677: WARNING/Worker-1] zimit has been called
zimwriterfs: unable to find welcome page at 'Valley/index.html. --welcome path/value must be relative to HTML_DIRECTORY.
[2015-05-09 07:30:47,634: ERROR/MainProcess] Task zimbalaka.prepare_zim[a93b1c6c-1cb0-45cf-b0b4-9849cfb13b03] raised unexpected: IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/var/www/zimbalaka/zim/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/zimbalaka/zim/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/zimbalaka/zim/zimbalaka.py", line 18, in prepare_zim
    zimfile = zimit(title, articles)
  File "/var/www/zimbalaka/zim/utils.py", line 130, in zimit
    shutil.copy(zimfile, newzim)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/tmp/tmpS6UNdu/Indus Valley Civilization.zim'
```

The zim was **NOT** generated because the spaces in the `title` field weren't properly escaped when `zimwriterfs` was run.

**Comment by tecoholic** [comment]
confirmed by the second trace:

```
[2015-05-09 10:01:29,233: INFO/MainProcess] Received task: zimbalaka.prepare_zim[67ae999c-677a-4d03-821f-15168a2fdcaf]
[2015-05-09 10:01:29,234: WARNING/Worker-1] zimit has been called
zimwriterfs: unable to find welcome page at 'Sindh/index.html. --welcome path/value must be relative to HTML_DIRECTORY.
[2015-05-09 10:02:18,897: ERROR/MainProcess] Task zimbalaka.prepare_zim[67ae999c-677a-4d03-821f-15168a2fdcaf] raised unexpected: IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/var/www/zimbalaka/zim/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/zimbalaka/zim/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/var/www/zimbalaka/zim/zimbalaka.py", line 18, in prepare_zim
    zimfile = zimit(title, articles)
  File "/var/www/zimbalaka/zim/utils.py", line 130, in zimit
    shutil.copy(zimfile, newzim)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/tmp/tmpS6UNdu/Amri, Sindh.zim'
[2015-05-09 10:43:15,784: INFO/MainProcess] Task zimbalaka.delete_zim[ea214f26-7652-4854-a92d-2050672bc4a0] succeeded in 0.00189527799375s: None
```
